# 第5章 配列生成

In [1]:
import numpy as np

## 40. 指定したN個の要素を持つ配列(要素は0から N-1 までの整数)をを生成するジェネレータ関数を定義し実行せよ

In [3]:
def generate(N):
    for x in range(N):
        yield x

In [4]:
for i in generate(10):
    print(i)

0
1
2
3
4
5
6
7
8
9


In [6]:
A = np.fromiter(generate(10),dtype=float)
print(A)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


## 41. sizeが10の0から1の実数配列を生成せよ。(ただし、0と1は除く)

In [7]:
np.linspace(0,1,12)[1:-1]

array([0.09090909, 0.18181818, 0.27272727, 0.36363636, 0.45454545,
       0.54545455, 0.63636364, 0.72727273, 0.81818182, 0.90909091])

In [17]:
np.linspace(0,1,11,endpoint=False)[1:]

array([0.09090909, 0.18181818, 0.27272727, 0.36363636, 0.45454545,
       0.54545455, 0.63636364, 0.72727273, 0.81818182, 0.90909091])

## 42. サイズ10の乱数ベクトルを生成し、昇順ソートせよ

In [21]:
%timeit np.sort(np.random.random(1000000))

572 ms ± 1.93 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [22]:
np.sort(np.random.random(1000000))

array([2.62300646e-06, 5.53280072e-06, 9.99255139e-06, ...,
       9.99998012e-01, 9.99998607e-01, 9.99999626e-01])

## 43. 小さいサイズの配列で np.sumよりも高速にsumせよ

In [28]:
a = np.arange(10)
# ufuncによる演算を連続で適用
%timeit np.add.reduce(a)
# C実装のufunc
%timeit np.sum(a)

13.8 µs ± 543 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)
40.5 µs ± 320 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [29]:
a = np.arange(10000)
# ufuncによる演算を連続で適用
%timeit np.add.reduce(a)
# C実装のufunc
%timeit np.sum(a)

44.9 µs ± 79.3 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)
72 µs ± 338 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)


## 44. 整数配列AとBが等しいかどうかを判定せよ

In [ ]:
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)

print(A)
print(B)

# 全ての要素が等しいか判定、 np.all()はスカラーとの比較もOK
%timeit eq = np.all(A==B)
print()

#全ての要素が等しいか判定