# 第3章 ようこそ、テンソルの深みへ

In [2]:
import numpy as np

## 20. 8 × 8 の行列を作成し、チェッカーボード模様を01で表現せよ

In [4]:
a = np.zeros((8,8), dtype=int)
for i in range(8):
    for j in range(8):
        if i % 2 == 0 and j % 2 == 0:
            a[i,j] = 1
        elif i % 2 == 1 and j % 2 == 1:
            a[i,j] = 1
        else:
            a[i,j] = 0
print(a)

[[1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]]


In [41]:
b =np.indices((8,8), dtype=int).sum(axis=0) % 2
print(b)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [20]:
matrix = np.zeros((8,8), dtype=int)
matrix[1::2,::2] = 1
matrix[::2,1::2] = 1
print(matrix)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [25]:
def a(n):
    matrix = np.zeros((n,n), dtype=int)
    for i in range(n):
        for j in range(n):
            if i % 2 == 0 and j % 2 == 0:
                matrix[i,j] = 1
            elif i % 2 == 1 and j % 2 == 1:
                matrix[i,j] = 1
            else:
                matrix[i,j] = 0
    return print(matrix)

def b(n):
    return print(np.indices((n,n), dtype=int).sum(axis=0) % 2)

def c(n):
    matrix = np.zeros((n,n), dtype=int)
    matrix[1::2,::2] = 1
    matrix[::2,1::2] = 1
    return print(matrix)

In [29]:
# %timeit a(8)
# %timeit b(8)
# %timeit c(8)
a(8)

[[1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]]


## 21. (6,6,6)の形の配列があったときに100番目の要素のインデックス(x,y,z)を求めよ

In [30]:
print(np.unravel_index(99,(6,6,6)))

(2, 4, 3)


## 22. tile関数を使って 8 × 8 のチェッカーボードを作れ

In [31]:
print(np.tile(np.array([[0,1],[1,0]]),(4,4)))

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


## 23. 5 × 5 の乱数配列を 0-1 に収まるように正規化せよ

In [47]:
a = np.random.random((5,5))
print(a)
print()
print((a - np.min(a))/(np.max(a) - np.min(a)))

[[0.20078573 0.37719719 0.32792667 0.72481901 0.42417323]
 [0.63047598 0.76597292 0.12465679 0.12847314 0.11539175]
 [0.98685894 0.56714524 0.79450645 0.56117867 0.41590426]
 [0.36417258 0.82234869 0.2348588  0.23874103 0.10058417]
 [0.11587809 0.87994064 0.98882242 0.75365559 0.31421803]]

[[0.11280932 0.31141759 0.25594765 0.70277861 0.36430435]
 [0.59656495 0.74911067 0.02710153 0.03139806 0.01667073]
 [0.99778947 0.52526568 0.78123441 0.51854837 0.35499495]
 [0.29675417 0.81257987 0.15116961 0.15554031 0.        ]
 [0.01721826 0.87741827 1.         0.73524352 0.24051413]]


## 24. xy座標軸上の整数を表すdtypeを自作せよ

In [54]:
mytype = np.dtype([('x',np.int),('y',np.int)])
a = np.array([(-1, 5),(3,8),(4,4)], dtype=mytype)
a

array([(-1, 5), ( 3, 8), ( 4, 4)], dtype=[('x', '<i8'), ('y', '<i8')])

## 25. RGBA(色の三原色 + 透明度)を表す独自のdtypeを作成せよ

In [59]:
color = np.dtype([('r',np.ubyte),('g',np.ubyte),('b',np.ubyte),('a',np.ubyte)])
test = np.array([(255,255,255,0.5)], dtype=color)
test

array([(255, 255, 255, 0)],
      dtype=[('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')])

## 26. 2 × 2 の行列と 2 × 2 の行列の行列積を求めよ

In [60]:
A = np.array([[1,2],[3,4]])
B = np.array([[1,2],[3,4]])
A @ B

array([[ 7, 10],
       [15, 22]])

## 27. 1次元の配列のうち要素が3から8の値となるものは符号反転した配列を生成せよ。Numpyを利用した場合としなかった場合の実行時間を計測せよ。

In [61]:
def negate38(a):
    l = []
    for i in a:
        if a[i] >= 3 and a[i] <= 8:
            l.append(-a[i])
        else:
            l.append(a[i])
    return l

a = np.arange(10)
%timeit negate38(a)
print(negate38(a))

124 µs ± 5.99 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)
[0, 1, 2, -3, -4, -5, -6, -7, -8, 9]


In [62]:
Z = np.arange(10)
%timeit Z[(3<=Z) & (Z<=8)] *= -1
Z

39.5 µs ± 112 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)


array([ 0,  1,  2, -3, -4, -5, -6, -7, -8,  9])

## 28. numpyをインポートしない状態でsum()メソッドを実行した場合と、numpyを*インポートした後にsum()を実行した場合とで結果を比較せよ

In [65]:
print(sum(range(5), -1)) # sum()　第二引数はstartを表す

from numpy import *
print(sum(range(5), -1)) #sum() 第二引数はaxisを表す

9
10


In [69]:
print(sum(range(5),0))
# print(sum(range(5),1)) #エラー

10


### point
####    axis

    二次元配列において
    axis = 0 は行方向
    axis = 1 は列方向

## 29. ベクトル　Zで次の表現のうち問題があるのはどれか?

In [76]:
import numpy as np

Z = np.array([1,2,3,4,5])
print(Z)

# 累乗
print(Z**Z)

#ビット演算　[2 << 1 >> 2] → 2を2新数で1bit左シフトし(4)、それを2ビット右シフトしている(1)
print(2<<Z>>2)

# Z < -Z の真偽値出力(True or False)
print(Z < -Z)

# 複素数jの掛け算
print(1j*Z)

# 二回除算
print(Z/1/1)

# Z<Z>Z　はスカラー値ならOK、今回はベクトルなのでNG
# print(Z<Z>Z)

[1 2 3 4 5]
[   1    4   27  256 3125]
[ 1  2  4  8 16]
[False False False False False]
[0.+1.j 0.+2.j 0.+3.j 0.+4.j 0.+5.j]
[1. 2. 3. 4. 5.]
